apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-contacts-app
  labels:
    app: flask-contacts-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-contacts-app
  template:
    metadata:
      labels:
        app: flask-contacts-app
    spec:
      containers:
      - name: flask-contacts-app
        image: shashkist/flask-contacts-app:latest
        ports:
        - containerPort: 5052
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: flask-mysql-config
              key: db_url
---
apiVersion: v1
kind: Service
metadata:
  name: flask-contacts-app-service
spec:
  selector:
    app: flask-contacts-app
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5052     
       
