apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec: 
      containers:
      - name: mysql
        image: mysql:latest  # The MySQL Docker image
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mysql  # Refers to a Secret named "secret-mysql"
              key: db_password  # The key for the password value in the Secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql  # MySQL's default data directory
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: ebs-pvc
